import {
  Entity, PrimaryGeneratedColumn, Column, CreateDateColumn,
  UpdateDateColumn, DeleteDateColumn, Index, OneToMany,
} from 'typeorm';
import { ExpenseRequestItemEntity } from './expense-request-item.entity';
import { ExpenseApprovalEntity } from './expense-approval.entity';
import { ExpenseAttachmentEntity } from './expense-attachment.entity';
import { ExpenseExecutionEntity } from './expense-execution.entity';

export type ExpenseRequestStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED_L1'
  | 'APPROVED'
  | 'EXECUTED'
  | 'REJECTED'
  | 'CANCELLED';

export type ExpenseType = 'PRE_APPROVAL' | 'POST_APPROVAL';
export type ExpenseFrequency = 'ONE_TIME' | 'RECURRING';
export type ExpensePeriod = 'MONTHLY' | 'QUARTERLY' | 'SEMI_ANNUAL' | 'ANNUAL';

export type ExpenseCategory =
  | 'TRANSPORTATION'
  | 'ENTERTAINMENT'
  | 'OFFICE_SUPPLIES'
  | 'MEALS'
  | 'SOFTWARE'
  | 'RENT'
  | 'UTILITIES'
  | 'MARKETING'
  | 'TRAINING'
  | 'HR_BENEFITS'
  | 'OTHER';

@Entity('amb_expense_requests')
@Index(['entId', 'exrStatus'])
@Index(['exrRequesterId'])
@Index(['exrNextDueDate'])
export class ExpenseRequestEntity {
  @PrimaryGeneratedColumn('uuid', { name: 'exr_id' })
  exrId: string;

  @Column({ name: 'ent_id' })
  entId: string;

  @Column({ name: 'exr_requester_id' })
  exrRequesterId: string;

  @Column({ name: 'exr_title', length: 200 })
  exrTitle: string;

  @Column({ name: 'exr_type', length: 20 })
  exrType: ExpenseType;

  @Column({ name: 'exr_frequency', length: 20, default: 'ONE_TIME' })
  exrFrequency: ExpenseFrequency;

  @Column({ name: 'exr_category', length: 50 })
  exrCategory: ExpenseCategory;

  @Column({ name: 'exr_expense_date', type: 'date' })
  exrExpenseDate: string;

  @Column({ name: 'exr_description', type: 'text', nullable: true })
  exrDescription: string | null;

  @Column({ name: 'exr_reason', type: 'text', nullable: true })
  exrReason: string | null;

  @Column({ name: 'exr_number', type: 'varchar', length: 30, unique: true, nullable: true })
  exrNumber: string | null;

  @Column({ name: 'exr_total_amount', type: 'decimal', precision: 18, scale: 2, default: 0 })
  exrTotalAmount: number;

  @Column({ name: 'exr_currency', length: 10, default: 'VND' })
  exrCurrency: string;

  // 정기 지출 필드
  @Column({ name: 'exr_period', type: 'varchar', length: 20, nullable: true })
  exrPeriod: ExpensePeriod | null;

  @Column({ name: 'exr_start_date', type: 'date', nullable: true })
  exrStartDate: string | null;

  @Column({ name: 'exr_end_date', type: 'date', nullable: true })
  exrEndDate: string | null;

  @Column({ name: 'exr_payment_day', type: 'int', nullable: true })
  exrPaymentDay: number | null;

  @Column({ name: 'exr_next_due_date', type: 'date', nullable: true })
  exrNextDueDate: string | null;

  @Column({ name: 'exr_status', length: 30, default: 'DRAFT' })
  exrStatus: ExpenseRequestStatus;

  @Column({ name: 'exr_parent_id', type: 'uuid', nullable: true })
  exrParentId: string | null;

  @Column({ name: 'exr_is_auto_generated', default: false })
  exrIsAutoGenerated: boolean;

  @Column({ name: 'exr_approver1_id', type: 'uuid', nullable: true })
  exrApprover1Id: string | null;

  @Column({ name: 'exr_approver2_id', type: 'uuid', nullable: true })
  exrApprover2Id: string | null;

  @CreateDateColumn({ name: 'exr_created_at' })
  exrCreatedAt: Date;

  @UpdateDateColumn({ name: 'exr_updated_at' })
  exrUpdatedAt: Date;

  @DeleteDateColumn({ name: 'exr_deleted_at' })
  exrDeletedAt: Date | null;

  // Relations
  @OneToMany(() => ExpenseRequestItemEntity, (item) => item.request, { cascade: true })
  items: ExpenseRequestItemEntity[];

  @OneToMany(() => ExpenseApprovalEntity, (ap) => ap.request)
  approvals: ExpenseApprovalEntity[];

  @OneToMany(() => ExpenseAttachmentEntity, (at) => at.request)
  attachments: ExpenseAttachmentEntity[];

  @OneToMany(() => ExpenseExecutionEntity, (ex) => ex.request)
  executions: ExpenseExecutionEntity[];
}
