import {
  CheckSquare,
  Bot,
  FileText,
  MessageCircle,
  CalendarDays,
  CalendarOff,
  CalendarCheck,
  Megaphone,
  FolderOpen,
  HardDrive,
  Landmark,
  Users,
  Receipt,
  Mail,
  Briefcase,
  Tags,
  Building2,
  AlertCircle,
  Calendar,
  Package,
  Globe,
  AppWindow,
  LayoutDashboard,
  Wallet,
  LucideIcon,
} from 'lucide-react';

export const WORK_TOOL_CODES = [
  'TODAY',
  'TODO',
  'MEETING_NOTES',
  'DRIVE',
  'AMOEBA_TALK',
  'ISSUES',
  'PROJECT_MANAGEMENT',
  'CALENDAR',
];

export const ICON_MAP: Record<string, LucideIcon> = {
  CheckSquare,
  Bot,
  FileText,
  MessageCircle,
  CalendarDays,
  CalendarOff,
  CalendarCheck,
  Megaphone,
  FolderOpen,
  HardDrive,
  Landmark,
  Users,
  Receipt,
  Mail,
  Briefcase,
  Tags,
  Building2,
  AlertCircle,
  Calendar,
  Package,
  Globe,
  AppWindow,
  LayoutDashboard,
  Wallet,
};

export const COLOR_MAP: Record<string, string> = {
  CheckSquare: 'text-green-500',
  Bot: 'text-indigo-500',
  FileText: 'text-amber-500',
  MessageCircle: 'text-blue-500',
  CalendarDays: 'text-cyan-500',
  CalendarOff: 'text-teal-500',
  Megaphone: 'text-amber-500',
  FolderOpen: 'text-purple-500',
  HardDrive: 'text-purple-500',
  Landmark: 'text-emerald-500',
  Users: 'text-teal-500',
  Receipt: 'text-orange-500',
  Mail: 'text-sky-500',
  Briefcase: 'text-violet-500',
  Tags: 'text-rose-500',
  Building2: 'text-cyan-600',
  AlertCircle: 'text-red-500',
  Calendar: 'text-teal-600',
  Package: 'text-amber-600',
  Globe: 'text-lime-600',
  AppWindow: 'text-fuchsia-500',
};

export const ICON_BG_MAP: Record<string, string> = {
  CheckSquare: 'bg-green-50',
  Bot: 'bg-indigo-50',
  FileText: 'bg-amber-50',
  MessageCircle: 'bg-blue-50',
  CalendarDays: 'bg-cyan-50',
  CalendarOff: 'bg-teal-50',
  Megaphone: 'bg-amber-50',
  FolderOpen: 'bg-purple-50',
  HardDrive: 'bg-purple-50',
  Landmark: 'bg-emerald-50',
  Users: 'bg-teal-50',
  Receipt: 'bg-orange-50',
  Mail: 'bg-sky-50',
  Briefcase: 'bg-violet-50',
  Tags: 'bg-rose-50',
  Building2: 'bg-cyan-50',
  AlertCircle: 'bg-red-50',
  Calendar: 'bg-teal-50',
  Package: 'bg-amber-50',
  Globe: 'bg-lime-50',
  AppWindow: 'bg-fuchsia-50',
};

export const MENU_DESC_KEY: Record<string, string> = {
  TODO: 'common:menuDesc.TODO',
  MEETING_NOTES: 'common:menuDesc.MEETING_NOTES',
  DRIVE: 'common:menuDesc.DRIVE',
  AMOEBA_TALK: 'common:menuDesc.AMOEBA_TALK',
  ATTENDANCE: 'common:menuDesc.ATTENDANCE',
  MY_LEAVE: 'common:menuDesc.MY_LEAVE',
  NOTICES: 'common:menuDesc.NOTICES',
  ISSUES: 'common:menuDesc.ISSUES',
  PROJECT_MANAGEMENT: 'common:menuDesc.PROJECT_MANAGEMENT',
  CALENDAR: 'common:menuDesc.CALENDAR',
  AGENTS: 'common:menuDesc.AGENTS',
  WORK_ITEMS: 'common:menuDesc.WORK_ITEMS',
  HR: 'common:menuDesc.HR',
  BILLING: 'common:menuDesc.BILLING',
  ACCOUNTING: 'common:menuDesc.ACCOUNTING',
  MAIL: 'common:menuDesc.MAIL',
  KMS: 'common:menuDesc.KMS',
  SERVICE_MANAGEMENT: 'common:menuDesc.SERVICE_MANAGEMENT',
  ASSET_MANAGEMENT: 'common:menuDesc.ASSET_MANAGEMENT',
  EXPENSE_REQUEST: 'common:menuDesc.EXPENSE_REQUEST',
};
