import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, LessThanOrEqual } from 'typeorm';
import { Cron } from '@nestjs/schedule';
import { ExpenseRequestEntity } from '../entity/expense-request.entity';
import { ExpenseRequestItemEntity } from '../entity/expense-request-item.entity';

@Injectable()
export class ExpenseRecurringService {
  private readonly logger = new Logger(ExpenseRecurringService.name);
  private isRunning = false;

  constructor(
    @InjectRepository(ExpenseRequestEntity)
    private readonly repo: Repository<ExpenseRequestEntity>,
    @InjectRepository(ExpenseRequestItemEntity)
    private readonly itemRepo: Repository<ExpenseRequestItemEntity>,
  ) {}

  /** 매일 자정(UTC+7 기준 00:00) 실행 */
  @Cron('0 17 * * *') // UTC 17:00 = Asia/Ho_Chi_Minh 00:00
  async processRecurringExpenses() {
    if (this.isRunning) {
      this.logger.warn('Recurring expense cron already running, skipping.');
      return;
    }
    this.isRunning = true;
    try {
      const today = new Date().toISOString().split('T')[0];
      await this.generateDueExpenses(today);
    } catch (err) {
      this.logger.error('Failed to process recurring expenses', err);
    } finally {
      this.isRunning = false;
    }
  }

  async generateDueExpenses(today: string): Promise<number> {
    const dueRequests = await this.repo.find({
      where: {
        exrFrequency: 'RECURRING' as any,
        exrStatus: 'APPROVED',
        exrNextDueDate: LessThanOrEqual(today) as any,
      },
      relations: ['items'],
    });

    let generated = 0;
    for (const parent of dueRequests) {
      try {
        await this.generateChildExpense(parent, today);
        await this.updateNextDueDate(parent);
        generated++;
      } catch (err) {
        this.logger.error(`Failed to generate child expense for ${parent.exrId}`, err);
      }
    }

    this.logger.log(`Generated ${generated} recurring expense(s) for ${today}`);
    return generated;
  }

  private async generateChildExpense(parent: ExpenseRequestEntity, today: string) {
    const child = this.repo.create({
      entId: parent.entId,
      exrRequesterId: parent.exrRequesterId,
      exrTitle: parent.exrTitle,
      exrType: parent.exrType,
      exrFrequency: 'ONE_TIME',
      exrCategory: parent.exrCategory,
      exrExpenseDate: today,
      exrDescription: parent.exrDescription,
      exrReason: parent.exrReason,
      exrCurrency: parent.exrCurrency,
      exrTotalAmount: parent.exrTotalAmount,
      exrStatus: 'DRAFT',
      exrParentId: parent.exrId,
      exrIsAutoGenerated: true,
      exrApprover1Id: parent.exrApprover1Id,
      exrApprover2Id: parent.exrApprover2Id,
    });
    const savedChild = await this.repo.save(child);

    if (parent.items?.length) {
      const items = parent.items.map((item) =>
        this.itemRepo.create({
          exrId: savedChild.exrId,
          eriName: item.eriName,
          eriQuantity: item.eriQuantity,
          eriUnitPrice: item.eriUnitPrice,
          eriTaxAmount: item.eriTaxAmount,
          eriCurrency: item.eriCurrency,
          eriNote: item.eriNote,
          eriSortOrder: item.eriSortOrder,
        }),
      );
      await this.itemRepo.save(items);
    }
  }

  private async updateNextDueDate(parent: ExpenseRequestEntity) {
    const next = this.calcNextDueDate(parent.exrNextDueDate!, parent.exrPeriod!, parent.exrPaymentDay);
    const isExpired = parent.exrEndDate && next > parent.exrEndDate;

    await this.repo.update(parent.exrId, {
      exrNextDueDate: isExpired ? null : next,
      exrStatus: isExpired ? 'CANCELLED' : 'APPROVED',
    });
  }

  private calcNextDueDate(current: string, period: string, paymentDay: number | null): string {
    const d = new Date(current);
    switch (period) {
      case 'MONTHLY':
        d.setMonth(d.getMonth() + 1);
        break;
      case 'QUARTERLY':
        d.setMonth(d.getMonth() + 3);
        break;
      case 'SEMI_ANNUAL':
        d.setMonth(d.getMonth() + 6);
        break;
      case 'ANNUAL':
        d.setFullYear(d.getFullYear() + 1);
        break;
    }
    if (paymentDay) {
      const maxDay = new Date(d.getFullYear(), d.getMonth() + 1, 0).getDate();
      d.setDate(Math.min(paymentDay, maxDay));
    }
    return d.toISOString().split('T')[0];
  }
}
