import { Injectable, Logger } from '@nestjs/common';
import { DocTypeEntity } from '../../entity/doc-type.entity';

interface SectionContent {
  code: string;
  name: string;
  order: number;
  content: string;
}

interface GenerateDto {
  audience: string;
  language: string;
  format: string;
  title?: string;
}

// Brand constants (matches pptx-generation.service.ts)
const BRAND = {
  primary: '#F5841F',
  secondary: '#1E293B',
  accent: '#3B82F6',
  background: '#FFFFFF',
  textDark: '#1E293B',
  textLight: '#64748B',
  fontTitle: 'Helvetica-Bold',
  fontBody: 'Helvetica',
};

@Injectable()
export class PdfGenerationService {
  private readonly logger = new Logger(PdfGenerationService.name);

  async generate(
    sections: SectionContent[],
    dto: GenerateDto,
    docType: DocTypeEntity,
  ): Promise<Buffer> {
    const PDFDocument = (await import('pdfkit')).default;

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 50, right: 50 },
        info: {
          Title: dto.title || docType.dtpName,
          Author: 'Amoeba Management System',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Cover page
      this.addCoverPage(doc, dto, docType);

      // Content pages
      for (const section of sections) {
        if (section.code === 'COVER') continue;
        this.addContentPage(doc, section);
      }

      // Closing page
      this.addClosingPage(doc, dto);

      doc.end();
    });
  }

  private addCoverPage(doc: any, dto: GenerateDto, docType: DocTypeEntity): void {
    // Background accent bar at top
    doc.rect(0, 0, doc.page.width, 8).fill(BRAND.primary);

    // Title area
    doc.moveDown(6);
    doc
      .font(BRAND.fontTitle)
      .fontSize(28)
      .fillColor(BRAND.secondary)
      .text(dto.title || docType.dtpName, { align: 'center' });

    doc.moveDown(0.5);
    doc
      .font(BRAND.fontBody)
      .fontSize(14)
      .fillColor(BRAND.textLight)
      .text(`${dto.audience} | ${new Date().getFullYear()}`, { align: 'center' });

    doc.moveDown(2);
    doc
      .font(BRAND.fontBody)
      .fontSize(10)
      .fillColor(BRAND.textLight)
      .text('Generated by Amoeba Management System', { align: 'center' });

    // Bottom accent bar
    doc.rect(0, doc.page.height - 8, doc.page.width, 8).fill(BRAND.primary);
  }

  private addContentPage(doc: any, section: SectionContent): void {
    doc.addPage();

    // Top bar
    doc.rect(0, 0, doc.page.width, 4).fill(BRAND.accent);

    // Section title
    doc
      .font(BRAND.fontTitle)
      .fontSize(18)
      .fillColor(BRAND.secondary)
      .text(section.name, 50, 40);

    // Divider
    doc.moveDown(0.3);
    const y = doc.y;
    doc.moveTo(50, y).lineTo(200, y).strokeColor(BRAND.primary).lineWidth(2).stroke();

    doc.moveDown(0.8);

    // Parse markdown-like content
    this.renderMarkdownContent(doc, section.content);
  }

  private renderMarkdownContent(doc: any, content: string): void {
    const lines = content.split('\n');
    const pageBottom = doc.page.height - doc.page.margins.bottom;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        doc.moveDown(0.3);
        continue;
      }

      // Check if we need a new page
      if (doc.y > pageBottom - 40) {
        doc.addPage();
        doc.rect(0, 0, doc.page.width, 4).fill(BRAND.accent);
        doc.y = 40;
      }

      // Heading
      if (trimmed.startsWith('### ')) {
        doc.moveDown(0.3);
        doc
          .font(BRAND.fontTitle)
          .fontSize(12)
          .fillColor(BRAND.secondary)
          .text(trimmed.replace(/^###\s+/, ''));
        doc.moveDown(0.2);
      } else if (trimmed.startsWith('## ')) {
        doc.moveDown(0.5);
        doc
          .font(BRAND.fontTitle)
          .fontSize(14)
          .fillColor(BRAND.secondary)
          .text(trimmed.replace(/^##\s+/, ''));
        doc.moveDown(0.3);
      } else if (trimmed.startsWith('# ')) {
        doc.moveDown(0.5);
        doc
          .font(BRAND.fontTitle)
          .fontSize(16)
          .fillColor(BRAND.secondary)
          .text(trimmed.replace(/^#\s+/, ''));
        doc.moveDown(0.3);
      }
      // Bullet point
      else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        const text = trimmed.replace(/^[-*]\s+/, '');
        const cleanText = text.replace(/\*\*([^*]+)\*\*/g, '$1');
        doc
          .font(BRAND.fontBody)
          .fontSize(10)
          .fillColor(BRAND.textDark)
          .text(`  •  ${cleanText}`, { indent: 10 });
      }
      // Numbered list
      else if (/^\d+\.\s/.test(trimmed)) {
        const cleanText = trimmed.replace(/\*\*([^*]+)\*\*/g, '$1');
        doc
          .font(BRAND.fontBody)
          .fontSize(10)
          .fillColor(BRAND.textDark)
          .text(`  ${cleanText}`, { indent: 10 });
      }
      // Regular text
      else {
        const cleanText = trimmed.replace(/\*\*([^*]+)\*\*/g, '$1');
        doc
          .font(BRAND.fontBody)
          .fontSize(10)
          .fillColor(BRAND.textDark)
          .text(cleanText);
      }
    }
  }

  private addClosingPage(doc: any, dto: GenerateDto): void {
    doc.addPage();

    doc.rect(0, 0, doc.page.width, doc.page.height).fill(BRAND.secondary);

    const thankYou =
      dto.language === 'ko' ? '감사합니다' : dto.language === 'vi' ? 'Cảm ơn' : 'Thank You';

    doc.moveDown(8);
    doc
      .font(BRAND.fontTitle)
      .fontSize(32)
      .fillColor('#FFFFFF')
      .text(thankYou, { align: 'center' });

    doc.moveDown(1);
    doc
      .font(BRAND.fontBody)
      .fontSize(12)
      .fillColor('#94A3B8')
      .text('Amoeba Corporation', { align: 'center' });
  }
}
