/* eslint-disable @typescript-eslint/no-explicit-any */
import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken, getDataSourceToken } from '@nestjs/typeorm';
import { BadRequestException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { createMockRepository, createMockQueryBuilder, createMockMailService } from '../../test/mock.helper';

// ── Entities
import { ExpenseRequestEntity } from './entity/expense-request.entity';
import { ExpenseRequestItemEntity } from './entity/expense-request-item.entity';
import { ExpenseApprovalEntity } from './entity/expense-approval.entity';
import { ExpenseAttachmentEntity } from './entity/expense-attachment.entity';

// ── Services under test
import { ExpenseNumberService } from './service/expense-number.service';
import { ExpenseRequestService } from './service/expense-request.service';
import { ExpenseApprovalService } from './service/expense-approval.service';
import { ExpenseRecurringService } from './service/expense-recurring.service';
import { MailService } from '../../infrastructure/external/mail/mail.service';

// ─────────────────────────────────────────────────────────────────────────────

const mockUser = (role: string, userId = 'user-1') =>
  ({ userId, role, entityId: 'ent-1', email: 'test@example.com' } as any);

const makeExpense = (overrides: Partial<ExpenseRequestEntity> = {}): ExpenseRequestEntity =>
  ({
    exrId: 'exr-1',
    entId: 'ent-1',
    exrNumber: null,
    exrTitle: '출장 교통비',
    exrStatus: 'DRAFT',
    exrType: 'PRE_APPROVAL',
    exrFrequency: 'ONE_TIME',
    exrCategory: 'TRANSPORTATION',
    exrExpenseDate: '2026-03-10',
    exrTotalAmount: 100000,
    exrRequesterId: 'user-1',
    exrApprover1Id: 'approver-1',
    exrApprover2Id: null,
    exrIsAutoGenerated: false,
    exrNextDueDate: null,
    exrParentId: null,
    exrCreatedAt: new Date(),
    exrUpdatedAt: new Date(),
    exrDeletedAt: null,
    items: [],
    ...overrides,
  } as any);

// ═════════════════════════════════════════════════════════════════════════════
// 1. ExpenseNumberService
// ═════════════════════════════════════════════════════════════════════════════
describe('ExpenseNumberService', () => {
  let service: ExpenseNumberService;
  let repo: ReturnType<typeof createMockRepository>;

  beforeEach(async () => {
    repo = createMockRepository();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ExpenseNumberService,
        { provide: getRepositoryToken(ExpenseRequestEntity), useValue: repo },
      ],
    }).compile();

    service = module.get(ExpenseNumberService);
  });

  describe('generateNumber', () => {
    it('첫 번째 채번은 EXP-YYYYMM-0001 형식이어야 한다', async () => {
      const qb = createMockQueryBuilder();
      qb.getCount.mockResolvedValue(0);
      repo.createQueryBuilder.mockReturnValue(qb);

      const result = await service.generateNumber('ent-1', '2026-03-10');
      expect(result).toBe('EXP-202603-0001');
    });

    it('기존 3건이 있으면 EXP-YYYYMM-0004 가 반환되어야 한다', async () => {
      const qb = createMockQueryBuilder();
      qb.getCount.mockResolvedValue(3);
      repo.createQueryBuilder.mockReturnValue(qb);

      const result = await service.generateNumber('ent-1', '2026-03-15');
      expect(result).toBe('EXP-202603-0004');
    });

    it('월이 바뀌면 별도 시퀀스로 채번되어야 한다', async () => {
      const qb = createMockQueryBuilder();
      qb.getCount.mockResolvedValue(0);
      repo.createQueryBuilder.mockReturnValue(qb);

      const result = await service.generateNumber('ent-1', '2026-04-01');
      expect(result).toBe('EXP-202604-0001');
    });
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// 2. ExpenseRequestService.findAll
// ═════════════════════════════════════════════════════════════════════════════
describe('ExpenseRequestService - findAll', () => {
  let service: ExpenseRequestService;
  let repo: ReturnType<typeof createMockRepository>;

  const mockDataSource = {
    transaction: jest.fn((cb: any) => cb({ create: jest.fn(), save: jest.fn() })),
  };

  beforeEach(async () => {
    repo = createMockRepository();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ExpenseRequestService,
        { provide: getRepositoryToken(ExpenseRequestEntity), useValue: repo },
        { provide: getRepositoryToken(ExpenseRequestItemEntity), useValue: createMockRepository() },
        { provide: getRepositoryToken(ExpenseAttachmentEntity), useValue: createMockRepository() },
        { provide: getDataSourceToken(), useValue: mockDataSource },
        {
          provide: ExpenseNumberService,
          useValue: { generateNumber: jest.fn().mockResolvedValue('EXP-202603-0001') },
        },
      ],
    }).compile();

    service = module.get(ExpenseRequestService);
  });

  it('MANAGER 권한은 전체 목록을 조회한다 — andWhere(uid) 조건 미적용', async () => {
    const qb = createMockQueryBuilder();
    qb.getManyAndCount.mockResolvedValue([[], 0]);
    repo.createQueryBuilder.mockReturnValue(qb);

    await service.findAll('ent-1', mockUser('MANAGER'), {});

    // MANAGER(roleLevel=3)는 userId 필터 없이 조회
    const andWhereCalls = qb.andWhere.mock.calls.map((c: any) => c[0] as string);
    const hasUserFilter = andWhereCalls.some((q: string) => q.includes('exrApprover1Id'));
    expect(hasUserFilter).toBe(false);
  });

  it('MEMBER 권한은 자신이 작성/승인자인 건만 조회한다 — andWhere(uid) 조건 적용', async () => {
    const qb = createMockQueryBuilder();
    qb.getManyAndCount.mockResolvedValue([[], 0]);
    repo.createQueryBuilder.mockReturnValue(qb);

    await service.findAll('ent-1', mockUser('MEMBER'), {});

    const andWhereCalls = qb.andWhere.mock.calls.map((c: any) => c[0] as string);
    const hasUserFilter = andWhereCalls.some((q: string) => q.includes('exrApprover1Id'));
    expect(hasUserFilter).toBe(true);
  });

  it('페이지네이션 파라미터가 올바르게 적용되어야 한다', async () => {
    const qb = createMockQueryBuilder();
    qb.getManyAndCount.mockResolvedValue([[makeExpense()], 1]);
    repo.createQueryBuilder.mockReturnValue(qb);

    const result = await service.findAll('ent-1', mockUser('MASTER'), { page: '2', limit: '10' } as any);

    expect(result.page).toBe(2);
    expect(result.limit).toBe(10);
    expect(qb.skip).toHaveBeenCalledWith(10);
    expect(qb.take).toHaveBeenCalledWith(10);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// 3. ExpenseApprovalService
// ═════════════════════════════════════════════════════════════════════════════
describe('ExpenseApprovalService', () => {
  let service: ExpenseApprovalService;
  let requestRepo: ReturnType<typeof createMockRepository>;
  let approvalRepo: ReturnType<typeof createMockRepository>;
  let numberService: { generateNumber: jest.Mock };
  let mailService: ReturnType<typeof createMockMailService>;

  beforeEach(async () => {
    requestRepo = createMockRepository();
    approvalRepo = createMockRepository();
    numberService = { generateNumber: jest.fn().mockResolvedValue('EXP-202603-0001') };
    mailService = createMockMailService();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ExpenseApprovalService,
        { provide: getRepositoryToken(ExpenseRequestEntity), useValue: requestRepo },
        { provide: getRepositoryToken(ExpenseApprovalEntity), useValue: approvalRepo },
        { provide: ExpenseNumberService, useValue: numberService },
        { provide: MailService, useValue: mailService },
      ],
    }).compile();

    service = module.get(ExpenseApprovalService);
  });

  const setupFindOne = (expense: Partial<ExpenseRequestEntity>) => {
    requestRepo.findOne.mockResolvedValue(makeExpense(expense));
    requestRepo.save.mockImplementation((e: any) => Promise.resolve(e));
    approvalRepo.create.mockImplementation((data: any) => data);
    approvalRepo.save.mockResolvedValue({});
  };

  // ── approve
  describe('approve', () => {
    it('지정된 1차 승인자가 PENDING 상태 결의서를 승인하면 APPROVED_L1로 전환', async () => {
      setupFindOne({ exrStatus: 'PENDING', exrApprover1Id: 'approver-1', exrApprover2Id: null });

      const result = await service.approve('exr-1', { comment: '승인합니다' }, mockUser('MANAGER', 'approver-1'), 'ent-1');
      expect(result.exrStatus).toBe('APPROVED');
    });

    it('2차 승인자가 있는 1차 승인 후 APPROVED_L1 상태가 되어야 한다', async () => {
      setupFindOne({
        exrStatus: 'PENDING',
        exrApprover1Id: 'approver-1',
        exrApprover2Id: 'approver-2',
      });

      const result = await service.approve('exr-1', {}, mockUser('MANAGER', 'approver-1'), 'ent-1');
      expect(result.exrStatus).toBe('APPROVED_L1');
    });

    it('MASTER 권한 사용자가 자가 승인 시 바로 APPROVED로 전환', async () => {
      setupFindOne({
        exrStatus: 'PENDING',
        exrApprover1Id: 'master-user',
        exrApprover2Id: null,
      });

      const result = await service.approve('exr-1', {}, mockUser('MASTER', 'master-user'), 'ent-1');
      expect(result.exrStatus).toBe('APPROVED');
    });

    it('지정된 승인자가 아닌 MEMBER가 승인하면 ForbiddenException이 발생해야 한다', async () => {
      setupFindOne({ exrStatus: 'PENDING', exrApprover1Id: 'approver-1' });

      await expect(
        service.approve('exr-1', {}, mockUser('MEMBER', 'other-user'), 'ent-1'),
      ).rejects.toThrow(ForbiddenException);
    });

    it('PENDING/APPROVED_L1 이외 상태에서 승인하면 BadRequestException 발생', async () => {
      setupFindOne({ exrStatus: 'DRAFT' });

      await expect(
        service.approve('exr-1', {}, mockUser('MASTER', 'approver-1'), 'ent-1'),
      ).rejects.toThrow(BadRequestException);
    });
  });

  // ── reject
  describe('reject', () => {
    it('1차 승인자가 PENDING 상태를 반려하면 REJECTED로 전환', async () => {
      setupFindOne({ exrStatus: 'PENDING', exrApprover1Id: 'approver-1' });

      const result = await service.reject('exr-1', { comment: '예산 초과' }, mockUser('MANAGER', 'approver-1'), 'ent-1');
      expect(result.exrStatus).toBe('REJECTED');
    });

    it('승인자가 아닌 사용자가 반려하면 ForbiddenException 발생', async () => {
      setupFindOne({ exrStatus: 'PENDING', exrApprover1Id: 'approver-1' });

      await expect(
        service.reject('exr-1', { comment: '반려' }, mockUser('MEMBER', 'other-user'), 'ent-1'),
      ).rejects.toThrow(ForbiddenException);
    });

    it('PENDING/APPROVED_L1 이외 상태에서 반려하면 BadRequestException 발생', async () => {
      setupFindOne({ exrStatus: 'APPROVED' });

      await expect(
        service.reject('exr-1', { comment: '반려' }, mockUser('MASTER', 'approver-1'), 'ent-1'),
      ).rejects.toThrow(BadRequestException);
    });
  });

  // ── submit
  describe('submit', () => {
    it('DRAFT 상태 결의서를 제출하면 PENDING으로 전환되어야 한다', async () => {
      setupFindOne({ exrStatus: 'DRAFT', exrApprover1Id: 'approver-1', exrRequesterId: 'user-1' });

      const result = await service.submit('exr-1', mockUser('MEMBER', 'user-1'), 'ent-1');
      expect(['PENDING', 'APPROVED']).toContain(result.exrStatus);
    });

    it('작성자가 아닌 사용자가 제출하면 ForbiddenException 발생', async () => {
      setupFindOne({ exrStatus: 'DRAFT', exrRequesterId: 'user-1' });

      await expect(
        service.submit('exr-1', mockUser('MEMBER', 'other-user'), 'ent-1'),
      ).rejects.toThrow(ForbiddenException);
    });

    it('DRAFT/REJECTED 이외 상태에서 제출하면 BadRequestException 발생', async () => {
      setupFindOne({ exrStatus: 'PENDING', exrRequesterId: 'user-1' });

      await expect(
        service.submit('exr-1', mockUser('MEMBER', 'user-1'), 'ent-1'),
      ).rejects.toThrow(BadRequestException);
    });
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// 4. ExpenseRecurringService
// ═════════════════════════════════════════════════════════════════════════════
describe('ExpenseRecurringService', () => {
  let service: ExpenseRecurringService;
  let repo: ReturnType<typeof createMockRepository>;
  let itemRepo: ReturnType<typeof createMockRepository>;

  beforeEach(async () => {
    repo = createMockRepository();
    itemRepo = createMockRepository();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ExpenseRecurringService,
        { provide: getRepositoryToken(ExpenseRequestEntity), useValue: repo },
        { provide: getRepositoryToken(ExpenseRequestItemEntity), useValue: itemRepo },
      ],
    }).compile();

    service = module.get(ExpenseRecurringService);
  });

  describe('generateDueExpenses', () => {
    it('만기된 정기 결의서로부터 자식 결의서가 생성되어야 한다', async () => {
      const parentExpense = makeExpense({
        exrFrequency: 'RECURRING' as any,
        exrStatus: 'APPROVED',
        exrNextDueDate: '2026-03-01',
        exrRecurringType: 'MONTHLY',
        items: [
          {
            eriId: 'item-1',
            exrId: 'exr-1',
            eriName: '임대비용',
            eriAmount: 500000,
            eriQuantity: 1,
            eriCreatedAt: new Date(),
          } as any,
        ],
      } as any);

      repo.find.mockResolvedValue([parentExpense]);
      repo.create.mockImplementation((data: any) => ({ ...data, exrId: 'exr-child-1' }));
      repo.save.mockImplementation((e: any) => Promise.resolve({ ...e, exrId: e.exrId || 'exr-child-1' }));
      itemRepo.create.mockImplementation((data: any) => data);
      itemRepo.save.mockResolvedValue({});

      const count = await service.generateDueExpenses('2026-03-10');
      expect(count).toBe(1);
      expect(repo.create).toHaveBeenCalledWith(
        expect.objectContaining({
          exrParentId: 'exr-1',
          exrIsAutoGenerated: true,
          exrStatus: 'DRAFT',
          exrFrequency: 'ONE_TIME',
        }),
      );
    });

    it('만기된 정기 결의서가 없으면 0을 반환해야 한다', async () => {
      repo.find.mockResolvedValue([]);

      const count = await service.generateDueExpenses('2026-03-10');
      expect(count).toBe(0);
    });
  });
});
