import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { TodoEntity } from '../../todo/entity/todo.entity';
import { UserEntity } from '../../auth/entity/user.entity';
import { InvoiceEntity } from '../entity/invoice.entity';

@Injectable()
export class InvoiceTodoService {
  constructor(
    @InjectRepository(TodoEntity)
    private readonly todoRepo: Repository<TodoEntity>,
    @InjectRepository(UserEntity)
    private readonly userRepo: Repository<UserEntity>,
  ) {}

  async createReviewTodo(invoice: InvoiceEntity, assignedUserId: string) {
    const partnerName = invoice.partner?.ptnCompanyName || '';
    await this.createTodo(
      assignedUserId,
      `Invoice review requested: ${invoice.invNumber}`,
      `Please review the invoice ${invoice.invNumber} for ${partnerName}. Amount: ${invoice.invCurrency} ${Number(invoice.invTotal).toLocaleString()}`,
    );
  }

  async createManagerApprovalTodo(invoice: InvoiceEntity, entityId: string) {
    const managers = await this.userRepo.find({
      where: [{ usrRole: 'MANAGER' }, { usrRole: 'ADMIN' }],
    });
    const partnerName = invoice.partner?.ptnCompanyName || '';
    for (const manager of managers) {
      await this.createTodo(
        manager.usrId,
        `Invoice approval requested: ${invoice.invNumber}`,
        `Invoice ${invoice.invNumber} for ${partnerName} needs your approval. Amount: ${invoice.invCurrency} ${Number(invoice.invTotal).toLocaleString()}`,
      );
    }
  }

  async createAdminApprovalTodo(invoice: InvoiceEntity, entityId: string) {
    const admins = await this.userRepo.find({
      where: { usrRole: 'ADMIN' },
    });
    const partnerName = invoice.partner?.ptnCompanyName || '';
    for (const admin of admins) {
      await this.createTodo(
        admin.usrId,
        `Invoice final approval: ${invoice.invNumber}`,
        `Invoice ${invoice.invNumber} for ${partnerName} needs your final approval. Amount: ${invoice.invCurrency} ${Number(invoice.invTotal).toLocaleString()}`,
      );
    }
  }

  async createSentNotificationTodo(invoice: InvoiceEntity, assignedUserId: string) {
    const partnerName = invoice.partner?.ptnCompanyName || '';
    await this.createTodo(
      assignedUserId,
      `Invoice approved: ${invoice.invNumber}`,
      `Invoice ${invoice.invNumber} for ${partnerName} has been approved and issued. It will be sent automatically.`,
    );
  }

  async createRejectionTodo(invoice: InvoiceEntity, assignedUserId: string, reason: string) {
    const partnerName = invoice.partner?.ptnCompanyName || '';
    await this.createTodo(
      assignedUserId,
      `Invoice rejected: ${invoice.invNumber}`,
      `Invoice ${invoice.invNumber} for ${partnerName} has been rejected. Reason: ${reason}`,
    );
  }

  async createAutoGeneratedTodo(invoice: InvoiceEntity, assignedUserId: string) {
    const partnerName = invoice.partner?.ptnCompanyName || '';
    await this.createTodo(
      assignedUserId,
      `Monthly invoice generated: ${invoice.invNumber}`,
      `Monthly invoice ${invoice.invNumber} for ${partnerName} has been auto-generated. Please review and submit for approval.`,
    );
  }

  private async createTodo(userId: string, title: string, description: string) {
    const todo = this.todoRepo.create({
      usrId: userId,
      tdoTitle: title,
      tdoDescription: description,
      tdoStatus: 'SCHEDULED',
      tdoDueDate: new Date(),
      tdoTags: 'BILLING',
    });
    await this.todoRepo.save(todo);
  }
}
